name: Python Lint and Test
run-name: lint and test on ${{ github.ref_name }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [3.8,3.9,3.10,3.11]
    steps:
      - uses: actions/checkout@v4
        name: get code
      - name: Flake8
        uses: microsoft/action-python@0.7.3
        with:
          flake8: true
          python_version: ${{ matrix.python_version }}
          workdir: '.'
          fail_on_error: true

  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: get code
      - name: Pytest
        uses: microsoft/action-python@0.7.3
        with:
          pytest: true
          workdir: '.'
          fail_on_error: true
